// Writes src/lib/ui-icons.js — { key: inner SVG markup } for <Icon name="…"> (96×96 viewBox, fills
// are the theme's --ic-* variables). Run `node design/ui-icons/build.mjs` after editing icons.js.
import { ICONS } from "./icons.js";
import { writeFileSync } from "node:fs";
const out = new URL("../../src/lib/ui-icons.js", import.meta.url);
const map = Object.fromEntries(ICONS.map(([key, , , body]) => [key, body()]));
writeFileSync(out, `// GENERATED by design/ui-icons/build.mjs — do not edit. The site's own UI icons (owner, 2026-09-29).\nexport const UI_ICONS = ${JSON.stringify(map, null, 0).replace(/","/g, '",\n  "')};\n`);
console.log(`src/lib/ui-icons.js: ${ICONS.length} icons`);
